### ISSUE TITLE
Decide on a Keynote Speaker

### ISSUE THREAD

**Issue by href** [SwissPy/sps18#7]
As previously discussed: We want to invite a keynote speaker again. The invitation itself will be another ticket. Here we should discuss who we would want to invite.

So please nominate anyone that you think would be a good fit.

**Comment by dbrgn** [comment]
Left a comment on Slack.

**Comment by sfkeller** [comment]
Really off topic regarding the call for location sps19, but since I forgot access to Slack I'll comment here: I'd just like to confirm that Rapperswil - i.e. HSR, my team and me - still are welcoming the Swiss Python Summit at "the most beautiful campus of Switzerland" ;-). Now, should Rapperswil apply as venue in the call too, or is it remaining the fallback anyway?

**Comment by href** [comment]
@sfkeller  You're not really the fallback, but the standard against the other venues have to measure up. That includes the support we get from you and your team ;)

To answer your question: No, I don't think you need to apply :)
